# Generated by Django 5.1.6 on 2025-03-05 17:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_paket', models.CharField(max_length=20, unique=True)),
                ('kecepatan', models.CharField(max_length=10)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('kontak', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('pelanggan', 'Pelanggan'), ('admin', 'Admin'), ('teknisi', 'Teknisi')], default='pelanggan', max_length=10)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Langganan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField(default=django.utils.timezone.now)),
                ('tanggal_berakhir', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frest.paket')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'pelanggan'}, on_delete=django.db.models.deletion.CASCADE, to='Frest.user')),
            ],
        ),
    ]
